name: ESLint
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches:
      - master
      - 'renovate/**'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Installs Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs all global dependencies
        run: npm i -g eslint
      - name: Lints the repository for any linting errors/warnings
        run: eslint src --ext .ts --fix