name: Kotlin CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java
        with:
          java-version: 1.8
      - name: Setup Gradle cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/cache
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys:
            ${{ runner.os }}-test-gradle-
      - name: Grant execution perms to Gradle
        run: chmod +x gradlew
      - name: Build the project (to see any failures)
        run: ./gradlew build